# Generated by Django 3.1 on 2020-08-22 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Element',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(blank=True, max_length=100, null=True)),
                ('text', models.CharField(blank=True, max_length=100, null=True)),
                ('tail', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'ordering': ['-tag'],
            },
        ),
        migrations.CreateModel(
            name='Parentship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currentElement', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent', to='xml_app.element')),
                ('parentElement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='current', to='xml_app.element')),
            ],
        ),
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute', models.CharField(blank=True, max_length=100, null=True)),
                ('element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xml_app.element')),
            ],
        ),
    ]
